name: pyimg
channels:
  - conda-forge
  - defaults
dependencies:
  - ipykernel
  - matplotlib
  - pandas
  - pip
  - pytest
  - setuptools
  - six
  - wheel
  - numpy
  - scikit-image
  - scipy
  - pillow
  - tk
  - opencv-python
